name: Backend build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
 GITHUB_TOKEN: ${{ github.token }}
 IMAGE_NAME: winter23-measurements

jobs:
 build:
      name: Build Artefact
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 17
        - run: mvn -B package --file pom.xml -DskipTests
          working-directory: measurements/measurements_backend
        - run: mkdir staging && cp target/*.jar staging/measurements_backend.jar
          working-directory: measurements/measurements_backend
        - uses: actions/upload-artifact@v1
          with:
            name: measurements_backend_jar
            path: /home/runner/work/winterferi2023/winterferi2023/measurements/measurements_backend/staging
        - name: QA - Sonar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: mvn -DskipTests -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=beranic_winter23QA -Dsonar.qualitygate.wait=true
          working-directory: measurements/measurements_backend
