name: Backend build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
 GITHUB_TOKEN: ${{ github.token }}
 IMAGE_NAME: winter23-measurements

jobs:
 build:
      name: Build Artefact
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 17
        - run: mvn -B package --file pom.xml -DskipTests
          working-directory: measurements/measurements_backend
        - run: mkdir staging && cp target/*.jar staging/measurements_backend.jar
          working-directory: measurements/measurements_backend
        - uses: actions/upload-artifact@v1
          with:
            name: measurements_backend_jar
            path: /home/runner/work/winterferi2023/winterferi2023/measurements/measurements_backend/staging
