# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend build&test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo $(pwd)
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: /home/runner/work/winterferi2023/winterferi2023/measurements/measurements_frontend/measurements/package-lock.json

    - run: npm ci
      working-directory: measurements/measurements_frontend/measurements
    - run: npm run build --if-present
      working-directory: measurements/measurements_frontend/measurements
    - run: npm test
      working-directory: measurements/measurements_frontend/measurements
